### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by maxxafari** [traveloka/styled-modules#14]
Can you upload/link a working example. 
I have followed the steps in:
- Installation
- Configuration
- Usage

But get the following error 

> Module parse failed: /Users/.../next/components/Top/styles.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.

package.json
`
{
  "scripts": {
    "dev": "next",
    "start": "next start",
    "build": "next build"
  },
  "dependencies": {
    "next": "^4.2.3",
    "now": "^9.2.7",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "styled-modules": "^0.2.4"
  },
  "devDependencies": {
    "babel-plugin-inline-react-svg": "^0.2.0",
    "css-loader": "^0.28.9",
    "stylelint-config-standard": "^18.0.0"
  }
}
`

next.config.js
`
// next.config.js
module.exports = (config, { dev }) => {
  config.module.rules.push(
    {
      test: /\.css$/,
      use: [
        'babel-loader',
        'styled-modules/loader',
        'css-loader?modules',
      ],
    }
  );
  return config;
};
`

.babelrc
`
{
  "presets": [ "next/babel" ],
  "plugins": [
    ["styled-modules/babel", {
      "pattern": "\\.css$"
    }],
    "inline-react-svg"
  ]
}
`

**Comment by sayuti-daniel** [comment]
You misconfigured the `next.config.js`, use the following snippet:
```js
module.exports = {
  webpack(config, { dev }) {
    config.module.rules.push({
      test: /\.css$/,
      use: ["babel-loader", "styled-modules/loader", "css-loader?modules"]
    });
    return config;
  }
};
```
