### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by ni742015** [traveloka/styled-modules#9]
With the latest version 4.1.4, I get this error. 

> Syntax Error: Unexpected token (3:22)
  1 | import _StyledModules from 'styled-modules/style';
  2 | import styles from './styles.css';
  3 | export default (() => <_StyledModules styles={[{
    |                       ^
  4 |   __hash: styles.__hash,
  5 |   __css: styles.__css
  6 | }]}>

**Comment by sayuti-daniel** [comment]
Hi @ni742015 thanks for reporting the issue. I'd like to apologize for the late response. I will close this issue for now. If you still encounter the issue, please reopen and share a working copy of your configuration/project.
